volumes:
  pg_data:
  static:  # Новый том для статики

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - django-network

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static  # Для сборки collectstatic
    depends_on:
      - db
    networks:
      - django-network

  frontend:
    build: ./frontend/
    env_file: .env
    networks:
      - django-network

  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/  # Отдача статики через nginx
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
    networks:
      - django-network

networks:
  django-network:
    driver: bridge
